apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: system
data:
  registry-username: YmFja3VwcmVnaXN0cnk=
  registry-passowrd: bXlkb2NrZXJpbWFnZXM=