# Define Role that allows operations on K8s pods/deployments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: manager-role
rules:
- apiGroups: ["*"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "update"]
- apiGroups: ["*"]
  resources: ["daemonsets"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["list", "watch"]
- apiGroups: ["*"]
  resources: ["events"]
  verbs: ["list", "create"]
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["get", "update", "list", "create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "create", "update"]